use std::fs;
use std::path::PathBuf;

fn main() {
    println!("cargo:rerun-if-changed=../engine-protocol/schema.json");

    let schema_path = PathBuf::from("../engine-protocol/schema.json");
    let schema_content = fs::read_to_string(&schema_path)
        .expect("schema.json not found — run `pnpm --filter @draft-sim/engine-protocol build` first");

    let schema: schemars::schema::RootSchema = serde_json::from_str(&schema_content)
        .expect("schema.json is not valid JSON Schema");

    let mut type_space = typify::TypeSpace::new(
        typify::TypeSpaceSettings::default()
            .with_struct_builder(true)
            .with_derive("Clone".to_string())
            .with_derive("Debug".to_string()),
    );
    type_space
        .add_root_schema(schema)
        .expect("typify failed to process schema");

    let contents = format!(
        "// AUTO-GENERATED by build.rs from ../engine-protocol/schema.json. Do not edit.\n#![allow(clippy::all, dead_code)]\n\n{}",
        prettyplease::unparse(&syn::parse2(type_space.to_stream()).unwrap()),
    );

    let out_path = PathBuf::from("src/protocol_types.rs");
    fs::write(out_path, contents).expect("failed to write protocol_types.rs");
}
